# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import infer_pb2 as infer__pb2


class InferenceStub(object):
  """run inference
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Predict = channel.unary_unary(
        '/Inference/Predict',
        request_serializer=infer__pb2.Image.SerializeToString,
        response_deserializer=infer__pb2.InferResults.FromString,
        )


class InferenceServicer(object):
  """run inference
  """

  def Predict(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_InferenceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Predict': grpc.unary_unary_rpc_method_handler(
          servicer.Predict,
          request_deserializer=infer__pb2.Image.FromString,
          response_serializer=infer__pb2.InferResults.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Inference', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
